[package]
name = "aoc2018"
version = "0.1.0"
authors = ["ntegan <ntegan1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.7.1"
regex = "1.4.2"
